/**
 * Todo is the core domain entity.
 *
 * Instances are created only by TodosRepository.create() and mutated only by
 * TodosService.update(). All fields except id and created_at are mutable via PATCH.
 */
export class Todo {
  /** 32-char hex string generated by crypto.randomBytes(16).toString('hex'). */
  id: string;

  /** Non-empty string, max 200 chars after trim. */
  title: string;

  /** Defaults to false at creation time. */
  completed: boolean;

  /** ISO8601 string or null when no due date is set. */
  due_at: string | null;

  /** ISO8601 string; set at creation time; immutable. */
  created_at: string;

  /** ISO8601 string; updated on every successful PATCH. */
  updated_at: string;
}
